name: default

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    # cache store
    - name: cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.29
    - name: Test
      run: |
        go test -v ./downloader/
        go test -v ./cmd/radibrary-cli/
    - name: Build (Linux)
      run: go build -race -ldflags "-extldflags '-static'" -o target/radibrary-cli cmd/radibrary-cli/*.go
    - name: Upload Artifact (Linux)
      uses: actions/upload-artifact@v2
      with:
        name: linux-binary
        path: target/radibrary-cli
    - name: Build (macOS)
      run: GOOS=macos GOARCH=amd64 go build -race -ldflags "-extldflags '-static'" -o target/radibrary-cli cmd/radibrary-cli/*.go
    - name: Upload Artifact (macOS)
      uses: actions/upload-artifact@v2
      with:
        name: macos-binary
        path: target/radibrary-cli